# Generated by Django 6.0.2 on 2026-03-14 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('conid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('capid', models.IntegerField(primary_key=True, serialize=False)),
                ('capname', models.CharField(unique=True)),
                ('conid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
